export default function Head() {
    return (
        <>
            <title>WWE 2K Platform</title>
            <meta
                content="width=device-width, initial-scale=1.0"
                name="viewport"
            />
            <meta charSet="utf-8" />
            <meta name="robots" content="noindex, nofollow" />
            <meta name="googlebot" content="noindex, nofollow" />
            <meta name="google" content="notranslate" />
            <meta name="format-detection" content="telephone=no" />
            <meta name="msapplication-tap-highlight" content="no" />
            <meta name="application-name" content="Next.js PWA Example" />

            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icons/icon-72x72.png" />
            <link rel="manifest" href="/manifest.webmanifest.json" />
            <link rel="apple-touch-icon" href="/icons/icon-72x72.png" />
            <meta name="theme-color" content="#000000" />
            <meta name="apple-mobile-web-app-capable" content="yes" />
            <meta
                name="apple-mobile-web-app-status-bar-style"
                content="black"
            />
            <meta
                name="apple-mobile-web-app-title"
                content="Next.js PWA Example"
            />
        </>
    );
}
